name: garbage_cleaning_service
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.0.1
  flutter_map: ^0.14.0
  http: ^0.13.4
  location: ^4.0.0-nullsafety.0
  shared_preferences: ^2.0.13
  sizer: ^2.0.15
  socket_io_client: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
